# This action will build a Java project with Gradle, but not upload the artifacts
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build
description: "This action will build a Java project with Gradle"

inputs:
  java:
    type: string
    required: false
    default: 8
    description: The Java version that should be used to build the project
  task:
    type: string
    required: false
    default: "build"
    description: The Gradle task to run to build the project

runs:
  using: "composite"
  if: "!contains(github.event.commits[0].message, '[no-build]')"
  steps:
    - uses: "actions/checkout@v4.1.7"
    - uses: "gradle/actions/wrapper-validation@v3.5.0"
    - name: Set up JDK
      uses: "actions/setup-java@v4.2.2"
      with:
        distribution: temurin
        java-version: ${{ inputs.java }}
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build jar with Gradle
      run: ./gradlew ${{ inputs.task }}
