# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: false
        default: "Artifact"
        description: "The name of the artifact when it's done building and uploaded"
      java:
        type: string
        required: false
        default: 8
        description: The Java version that should be used to build the project
      path:
        type: string
        required: false
        default: build/libs
        description: The path to the built files to be uploaded as artifacts
      task:
        type: string
        required: false
        default: "build"
        description: The Gradle task to run to build the project

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[no-build]')"
    steps:
      - uses: "actions/checkout@v4.1.1"
      - uses: "gradle/wrapper-validation-action@v2.1.2"
      - name: Set up JDK
        uses: "actions/setup-java@v4.2.1"
        with:
          distribution: temurin
          java-version: ${{ inputs.java }}
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build jar with Gradle
        run: ./gradlew ${{ inputs.task }}
      - name: Upload artifacts
        uses: "actions/upload-artifact@v4.3.1"
        with:
          name: ${{ inputs.name }}
          path: ${{ inputs.path }}
