# This workflow will build a Java project with Gradle, upload the artifacts to the action, and publish them to Maven
# For more information see:
#   - https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
#   - https://reposilite.com/guide/github

name: Maven Publish
on:
  workflow_call:
    inputs:
      channel:
        type: string
        required: true
        description: "The release channel to publish to (ex: snapshots)"
      maven_url:
        type: string
        required: false
        default: "https://repo.srnyx.com"
        description: "The URL of the repository to publish to (NO trailing /)"
      version:
        type: string
        required: false
        description: "The version of the artifact (default: release tag if channel is releases, commit SHA if not)"
      name:
        type: string
        required: false
        default: "Artifact"
        description: "The name of the artifact when it's done building and uploaded"
      java:
        type: string
        required: false
        default: 21
        description: The Java version that should be used to build the project
      path:
        type: string
        required: false
        default: __default__
        description: The path to the built files to be uploaded as artifacts
      build_tool:
        type: string
        required: false
        default: auto
        description: auto, gradle, or maven
      task:
        type: string
        required: false
        default: __default__
        description: The task to run to build and publish the project
    secrets:
      MAVEN_NAME:
        required: true
        description: Maven username
      MAVEN_SECRET:
        required: true
        description: Maven secret (password)

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[no-build]')"
    steps:
      - uses: "actions/checkout@v6.0.2"
        with:
          fetch-depth: 0
      
      - name: Build context
        id: context
        shell: bash
        run: |
          # Build tool
          tool=""
          if [[ "${{ inputs.build_tool }}" != "auto" ]]; then
            tool="${{ inputs.build_tool }}"
          elif [[ -f "gradlew" ]]; then
            tool="gradle"
          elif [[ -f "pom.xml" ]]; then
            tool="maven"
          elif [[ -f "build.sbt" ]]; then
            tool="sbt"
          fi
          if [[ "$tool" != "gradle" && "$tool" != "maven" && "$tool" != "sbt" ]]; then
            echo "No supported build tool found!"
            exit 1
          fi
          echo "tool=$tool" >> "$GITHUB_OUTPUT"
      
          # Cache type (only valid ones)
          if [[ "$tool" == "gradle" || "$tool" == "maven" || "$tool" == "sbt" ]]; then
            echo "cache=$tool" >> "$GITHUB_OUTPUT"
          else
            echo "cache=" >> "$GITHUB_OUTPUT"
          fi
      
          # Command
          if [[ "$tool" == "gradle" ]]; then
            base="./gradlew"
          elif [[ "$tool" == "maven" ]]; then
            base="mvn"
          elif [[ "$tool" == "sbt" ]]; then
            base="sbt"
          fi
          if [[ "${{ inputs.task }}" != "__default__" ]]; then
            arguments="${{ inputs.task }}"
          elif [[ "$tool" == "gradle" ]]; then
            arguments="build publish"
          elif [[ "$tool" == "maven" ]]; then
            arguments="clean deploy"
          elif [[ "$tool" == "sbt" ]]; then
            arguments="publish"
          fi
          echo "command=$base $arguments" >> "$GITHUB_OUTPUT"
      
          # Artifact path
          if [[ "${{ inputs.path }}" != "__default__" ]]; then
            echo "path=${{ inputs.path }}" >> "$GITHUB_OUTPUT"
          elif [[ "$tool" == "gradle" ]]; then
            echo "path=**/build/libs" >> "$GITHUB_OUTPUT"
          elif [[ "$tool" == "maven" || "$tool" == "sbt" ]]; then
            echo "path=**/target/*.jar" >> "$GITHUB_OUTPUT"
          fi
          
      - name: Get version
        id: version
        run: |
          if [[ -n "${{ inputs.version }}" ]]; then
            version="${{ inputs.version }}"
          elif [[ "${{ inputs.channel }}" == "releases" ]]; then
            version="${GITHUB_REF_NAME}"
          else
            version="${GITHUB_SHA::7}"
          fi
          echo "version=$version" >> $GITHUB_OUTPUT
          
      - uses: "gradle/actions/wrapper-validation@v6.1.0"
        if: steps.context.outputs.tool == 'gradle'
        
      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: ${{ inputs.java }}
          cache: ${{ steps.context.outputs.cache }}
          
      - name: Grant execute permission for gradlew
        if: steps.context.outputs.tool == 'gradle'
        run: chmod +x gradlew
        
      - name: Build and publish jar
        run: ${{ steps.context.outputs.command }}
        env:
          VERSION: ${{ steps.version.outputs.version }}
          MAVEN_URL: ${{ inputs.maven_url }}/${{ inputs.channel }}
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
          
      - name: Upload artifacts to action
        uses: "actions/upload-artifact@v7.0.1"
        with:
          name: ${{ inputs.name }}
          path: ${{ steps.context.outputs.path }}
