# This workflow will build a Java project with Gradle and publish the artifacts to GitHub, Modrinth, and CurseForge
# For more information see: https://github.com/Kir-Antipov/mc-publish

name: Publish
on:
  workflow_call:
    inputs:
      java:
        type: string
        required: false
        default: 21
        description: The Java version that should be used to build the project
      task:
        type: string
        required: false
        default: "build publishMods"
        description: The Gradle task to run to build the project
      files:
        type: string
        required: false
        default: build/libs/*.jar
        description: The location of the built files to upload
    secrets:
      MODRINTH_TOKEN:
        required: false
        description: Modrinth token
      CURSEFORGE_TOKEN:
        required: false
        description: CurseForge token

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          
      - uses: gradle/actions/wrapper-validation@v6
      
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java }}
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build jar with Gradle
        run: ./gradlew ${{ inputs.task }}
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          
      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ inputs.files }}
