# This workflow will build a Java project with Gradle, upload the artifacts to the action/release, and publish them to platforms
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Platform Publish
on:
  workflow_call:
    inputs:
      name:
        type: string
        required: false
        default: ""
        description: "The name of the artifact when it's done building and uploaded"
      java:
        type: string
        required: false
        default: 21
        description: The Java version that should be used to build the project
      path:
        type: string
        required: false
        default: "build/libs/*.jar"
        description: The path to the built files to be uploaded as artifacts
      task:
        type: string
        required: false
        default: build publishMods
        description: The task to run to build the project
    secrets:
      MODRINTH_TOKEN:
        required: false
        description: Modrinth token (if platform-publishing)
      CURSEFORGE_TOKEN:
        required: false
        description: CurseForge token (if platform-publishing)

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "github.event_name == 'release' || !contains(github.event.commits[0].message, '[no-build]')"
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          
      - uses: gradle/actions/wrapper-validation@v6
      
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java }}
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build jar
        run: ./gradlew ${{ inputs.task }}
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          
      - name: Upload to action
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.name || github.event.repository.name }}
          path: ${{ inputs.path }}
          
      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: ${{ inputs.path }}
